### ISSUE TITLE
Add collection that can be extended easilly

### ISSUE THREAD

**Issue by yvoyer** [yvoyer/collection#17]
Extending the `TypedCollection` means that we have to override the construct, doing so breaks the static creation on the filter, partition and matching methods.

We should have a way to specify the arguments on the contruct...

Ex.

```
SomeCollection
{
    public function __construct($dep1, $dep2, $dep3)
    {
        parent::__construct('SomeClass');
    }
}

SomeOtherCollection
{
    public function __construct($dep1)
    {
        parent::__construct('SomeClass');
    }
}
```

Both cases should work

**Comment by bcolucci** [comment]
Need that :)

**Comment by yvoyer** [comment]
@bcolucci , You can have a look at #18 to see if it fix the need.
